In [1]:
import numpy as np

a = np.array([10,20,30])
b = np.array([40,50,60])

In [2]:
a.itemsize
b.itemsize

8

In [3]:
a.__array_interface__["data"][0]

1894187677504

In [4]:
import time

start = time.time()
l = list(range(9999999))
for i in l:
    l[i] = l[i]**2
end = time.time()
print(end - start)

5.037042140960693


In [5]:
import numpy as np

np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [6]:
np.ones((5,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [7]:
a = np.identity(5, dtype = int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [8]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [9]:
np.full_like(a, 8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

***Indexing and slicing***

In [10]:
a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])
c = np.array([[[1,2],[3,4]],
              
              [[5,6],[7,8]]])

In [11]:
a[0]
b[0,1]
c[0,1,1]

np.int64(4)

In [12]:
a[::-1]
b[::-1, ::-1]
c[::-1, ::-1, ::-1]

array([[[8, 7],
        [6, 5]],

       [[4, 3],
        [2, 1]]])

In [13]:
a+10

array([11, 12, 13])

In [15]:
np.max(a)

np.int64(3)

In [16]:
np.max(a, axis = 0)

np.int64(3)

In [19]:
np.max(b, axis = 1)

array([2, 4])

In [21]:
np.min(b)

np.int64(1)

In [22]:
np.min(b, axis = 0)

array([1, 2])

In [23]:
np.min(c, axis = 2)

array([[1, 3],
       [5, 7]])

In [24]:
np.min(c, axis = 2)

array([[1, 3],
       [5, 7]])

In [25]:
np.mean(a)

np.float64(2.0)

In [26]:
np.mean(b)

np.float64(2.5)

In [27]:
np.mean(c)

np.float64(4.5)

In [2]:
import pandas as pd
import numpy as np

In [11]:
a = pd.Series([10,20,30.0], index = ['a', 'b', 'c'])

In [12]:
a

a    10.0
b    20.0
c    30.0
dtype: float64

In [13]:
d = { 'hit' : 10, 'san' : 50, 'mindri' : 30}
pd.Series(d, name = 'Marks')

hit       10
san       50
mindri    30
Name: Marks, dtype: int64